language: node_js
cache: yarn
node_js:
- node
script: yarn start & yarn test && yarn lint
deploy:
  provider: npm
  email: npm@netflix.com
  on:
    tags: true
  api_key:
    secure: H7xAHJSzyQTUvE25umtTvUrnKNj1KV24cffrUCqb7+RUpm9Ikr6RuTqn3JjIMlE0qch0FURj5C4s4thZqmMOFg/LK0Ou+V9Hr0uNxL1lc7rJibGEuHi75I7A3x9tDyrSjIai3Xj2bJx900/r8Z3VzRye8Ui8z1Kxw4Lrkddpwigtz7YGHW4Sp/whWT+Cgsr0aAcON04ECeJpL9ZRU095q2FUiuI2Ezn+laBQ7bgebkZnyUBAosojaSP5j7eQPBdLk1WF5m2KICHdutote0o/Z6drCxGx1FO6sbcFn9HBjqrtBZYHfUC/stsEEEW+jFMD7I+wimewnUmUFpFEfNbJT9XhceL5kZb7FoLMwlRbJvr2alzs7WTIxTJ7W0PruBUQCPl1UEJWdNp3y6P3Vy2K9v+6XH9rX8b9vC9Q55EeUAfFwXdITOUNiKE9k8mjYe48uTczC9TVCi3WsYQ7hBKzjGpbnUiKQDg3UhuFuaJwrUKz413IHpC2vuTho5Fp52m94il2anLHP9ZJP3V1v84r8OKfxF2s9DXhLNfGIGXColQf4rpZGRYVstcH7otSClTrjS9tDlCfCGaq4KxJkv+bItnGQdOvaAjpJ/DQrbqDebVHQpYDilfKJdN00+ZdNHEBvBnGSjrpj30UP7ny/GQ4PxT8QFikhtaQJZvgv0Ypwxk=
