language: node_js
cache: yarn
node_js:
- node
script: yarn start & yarn test
deploy:
  provider: npm
  email: npm@netflix.com
  on:
    tags: true
  api_key:
    secure: yEvN5cMdd3T+WUDLRrErrDsBwTL1LqQhdqNwNLx3PDEuZINC+RQdCwl4c5+KIr9LbEQMOPd75tmkDLTquWjwsRuglRd1QVXHXNOBXPz1PIDRQ2oo2rDrKrdXfssVcZNcsdpnzTsb/ZHx9eBlQo96dWaHTGwJvYX9WHbPxbnolmQS5Cd8jtpRveV6CZ8VnCLpRucFrJzSzlc2f3SlYDMg6yd1Ub+fFs6yC6x1o09i5pmKeZNAeom5+f4XFpOD39d9zCk45Sm3QOnC0RiPitOCdMHmWZ+RQvNRccJeu7YZgqjaUgOq6aRBTKT1Yp9TYJ1RJCGthA33lZGmxlkfTSY7Tpnb3Xe5L0LCtkTC/ZitJ9lqGNk3c50a+waQv1+cKS4A1rxi2FpyVmDLMoIk50ux/ZUVGrJGju/gbrs3Fkgf+LM2pcu+9Z56iv46WUDeyej/3X1UFOxZMNQ1ny2lZV1JGSP3e2isQFQVV6xHqJ8ktilVoGwuDV5qlPL+2xdmQOeE4QssUTRHqVk0XWKmK+J8W0ae3xsZT2WoC+tzO9/7z3IpIuSCtGmWkg4zSlZpuKUg4LDfKmmM++zKjMkJ44JO7YddRU+RpmxuiLUp3REHVFMZY90+aBUl9z9DNVp7CWP8ZD/Is5HbZaHGPgaABD2PiOnPurQjpog1b2/f0Vo5x9A=
