language: node_js
cache: yarn
node_js:
- node
script: yarn start & yarn test && yarn lint-strict
deploy:
  provider: npm
  email: npm@netflix.com
  on:
    tags: true
  api_key:
    secure: dFMo6mcApR2BsW0lyoygvWeMJ6WclCAuAdaNZvU6p5vkSFGDIlMah6Soj+RhICV/0ebiPLx1zaD8uLPxD5DeqFtFZCuvT2oqvML7pFOJB/DrHwohZpavKen5bAgXMYdjyXOV98lCY/ZKkbDjgxjjbMmHGt2l7R+FXW5BGDFFqSEMzYBG7o969+VgxpBPDXmxjKcDAAyfUzcEFTpXHxRBPQhWX0Np1ruP0hbw4YKsTmbH+i0uSb/9Wx2xRRNGL/+eZikKY3f0A9UDo7kZXOwZg24e07/wXxGBzs03o+oHc1jeCMNMUHbA1i/28s5xtTh7JJTE7K6Aar2btsNYtBFwQpB7v+sDwaVmQBzIfc2Y/HHZxWDQAY1BgF6au/E4jIPKMpH7pgqX2NKOB7flQq9q4DZZf9/ZHjlqn8MBFTIEwgrAtxoQX4lyaMN4WVDmubra/ZGDCE8xpz7b3ERIbdyU6rTpHupKixauFQw8D1/zzLFDd5X7cso1RXZmBL56hO/Omjdsaqi56e18qNg3aGJvXjIvj9Vxu1vfooQONvUOpf/PTgbwj0dqifZt/j1+lXuFHECpUKrOlz6gfEh6CpoXBXFXXjce5MJO9Oit9e7xBQy7yzdyaZnIERmAClSrUUSSnjtmFaHvawbwoBjUa9pZPHUtiScBsq1bdlj73oLWQmE=
